<?php
/**
 * @file
 * Provides a custom entity type name 'mhinstall' for tracking Manufactured home installations.
 */

/**
 * Implements hook_entity_info().
 */
function mhinstall_entity_info() {
  $info = array();
  // The custom mhinstall entity is defined here.
  // See http://drupal.org/node/1026420 and http://drupal.org/node/878804
  // for more documentation.
  $info['mhinstall'] = array(
    // Human readable label
    'label' => t('MH Install'),
    // Table for storing entity data, defined in hook_schema().
    'base table' => 'mhinstall_mhinstall',
    // This helps Entity API know how to query the custom table.
    'entity keys' => array(
      'id' => 'id',
      'label' => 'label',
    ),
    'uri callback' => 'entity_class_uri',
    // Default class is 'Entity',
    'entity class' => 'MHInstallEntity',
    // Default class is 'EntityAPIController',
    'controller class' => 'MHInstallEntityController',
    // The information below is used to extend the EntityDefaultUIController.
    'admin ui' => array(
      'path' => 'admin/structure/mhinstall',
      'controller class' => 'MHInstallEntityUIController',
      'menu wildcard' => '%mhinstall',
      'file' => 'mhinstall.admin.inc',
    ),
    'module' => 'mhinstall',
    // This controls who can access entity CRUD.
    'access callback' => 'mhinstall_access'
  );
  return $info;
}

/**
 * Implements hook_menu().
 */
function mhinstall_menu() {
  $items = array();
  // Testing purposes.
  $items['mhinstall_entity'] = array(
    'title' => 'MH Install Demo page',
    'page callback' => 'mhinstall_demo_page',
    'access callback' => TRUE,
    'menu' => 'navigation',
  );
  $items['mhinstall/%mhinstall'] = array(
    'title' => 'MH Install',
    'page callback' => 'mhinstall_view_entity',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Menu autoloader for /mhinstall/%mhinstall.
 */
function mhinstall_load($id) {
  $mhinstall = entity_load('mhinstall', array($id));
  return array_pop($mhinstall);
}

/**
 * Callback for /mhinstall-entity.
 *
 * This is for testing purposes and can be deleted if no longer needed.
 */
function mhinstall_demo_page() {
  // Load and display an entity (don't forget to add one to the database first).
  $mhinstall = entity_load('mhinstall', array(1));
  dsm($mhinstall);

  return 'Have to return something or the page won\'t show up';
}

/**
 * Callback for /mhinstall/ID page.
 *
 * A place to render a complete video entity.
 */
function mhinstall_view_entity($mhinstall) {
  $mhinstall_entity = entity_view('mhinstall', array($mhinstall->id => $mhinstall));
  dsm($mhinstall_entity);
  return 'Hello World';
}

/**
 * Access callback for mhinstall CRUD operations.
 */
function mhinstall_access($op, $mhinstall = NULL, $account = NULL) {
  if ($op == 'view' && user_access('view mhinstalls', $account)) {
    return TRUE;
  }
  else if (user_access('administer mhinstalls', $account)) {
    return TRUE;
  }
}

/**
 * Implements hook_permission().
 */
function mhinstall_permission() {
  return array(
    'view mhinstalls' => array(
      'title' => t('View MH Install Entities'),      
    ),
    'administer mhinstalls' => array(
      'title' => t('Administer MH Install Entities'),
    ),
  );
}
/**
 * Custom entity class.
 * The class being overriden is located in:
 * sites/all/modules/contrib/entity/includes/entity.inc
 */
class MHInstallEntity extends Entity{
  /**
   * Override this in order to implement a custom default URI.
   */
  protected function defaultUri() {
    return array('path' => 'mhinstall/' . $this->identifier());
  }
}

/**
 * Our custom controller for the mhinstall type.
 *
 * We're choosing to extend the controller provided by the entity module for
 * full CRUD support for mhinstall.
 *
 * The EntityAPIController is found in
 * sites/all/modules/contrib/entity/includes/entity.controller.inc
 */
class MHInstallEntityController extends EntityAPIController {

}

/**
 * Our custom controller for the admin ui.
 *
 * The EntityDefaultUIController can be found in
 * sites/all/modules/contrib/entity/includes/entity.ui.inc
 */
class MHInstallEntityUIController extends EntityDefaultUIController {

}

