<?php
/**
 * @file
 * Provides a custom entity type name 'mhinstall_community'.
 */

/**
 * Implements hook_entity_info().
 */
function mhinstall_community_entity_info() {
  $info = array();
  // The custom mhinstall_community entity is defined here.
  // See http://drupal.org/node/1026420 and http://drupal.org/node/878804
  // for more documentation.
  $info['mhinstall_community'] = array(
    // Human readable label
    'label' => t('Community'),
    'plural label' => t('Communities'),
    'description' => t('Use to store information about MH Communities.'),
    // Table for storing entity data, defined in hook_schema().
    'base table' => 'mhinstall_community',
    // This helps Entity API know how to query the custom table.
    'entity keys' => array(
      'id' => 'id',
      'label' => 'label',
    ),
    // A simple wrapper around the uri method in the controller class.
    'uri callback' => 'entity_class_uri',
    // Default class is 'Entity',
    'entity class' => 'MHInstallCommunityEntity',
    // Default class is 'EntityAPIController',
    'controller class' => 'MHInstallCommunityEntityController',
    // The information below is used to extend the EntityDefaultUIController.
    'admin ui' => array(
      'path' => 'admin/mh-install/data-types/mhinstall_community',
      'controller class' => 'MHInstallCommunityEntityUIController',
      'menu wildcard' => '%mhinstall_community',
      'file' => 'mhinstall_community.admin.inc',
    ),
    'module' => 'mhinstall_community',
    // This controls who can access entity CRUD.
    'access callback' => 'mhinstall_community_access',
    'fieldable' => TRUE,
    'bundles' => array(
      'mhinstall_community' => array(
        'label' => t('Community'),
        'admin' => array(
          'path' => 'admin/mh-install/data-types/mhinstall_community',
          'access arguments' => array('administer mhinstall_community'),
        ),
      ),
    ),
    'views controller class' => 'EntityDefaultViewsController',
    'view modes' => array(
      'custom_view1' => array(
        'label' => t('Custom View 1'),
        'custom settings' => FALSE,
      ),      
    ),
  );
  return $info;
}

/**
 * Implements hook_entity_property_info().
 */
function mhinstall_community_entity_property_info() {
  $info = array();
  $properties = &$info['mhinstall_community']['properties'];
  $properties['id'] = array(
    'label' => t('EID'),
    'description' => t('The unique, numeric, internal ID of the MH Install Community entity.'),
    'type' => 'integer',
    'schema field' => 'id',
  );
  $properties['label'] = array(
    'label' => t('MH Install Community entity ID'),
    'description' => t('The unique human readable ID of the MH Install Community entity.'),
    'type' => 'text',
    'schema field' => 'label',
  );
  $properties['created'] = array(
    'label' => t('Created date'),
    'description' => t('The date the MH Install Community entity was created.'),
    'type' => 'date',
    'schema field' => 'created',
  );
  $properties['updated'] = array(
    'label' => t('Updated date'),
    'description' => t('The date the MH Install Community entity was last updated.'),
    'type' => 'date',
    'schema field' => 'updated',
  );
  return $info;
}

/**
 * Implements hook_menu().
 */
function mhinstall_community_menu() {
  $items = array();
  $items['mhinstall_community/%mhinstall_community'] = array(
    'title' => 'MH Install Community entity',
    'page callback' => 'mhinstall_community_view_entity',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Menu autoloader for /mhinstall_community/%mhinstall_community.
 */
function mhinstall_community_load($id) {
  $mhinstall_community = entity_load('mhinstall_community', array($id));
  return array_pop($mhinstall_community);
}

/**
 * Callback for /mhinstall_community/ID page.
 *
 * A place to render a complete video entity.
 */
function mhinstall_community_view_entity($mhinstall_community) {
  // Use any of the view modes defined in hook_entity_info().
  $viewmode = 'full'; 
  drupal_set_title($mhinstall_community->label);
  $mhinstall_community_view = entity_view('mhinstall_community', array($mhinstall_community->id => $mhinstall_community), $viewmode);
  dsm($mhinstall_community, 'The results from entity_load()');
  dsm($mhinstall_community_view, 'The results from entity_view()');
  return $mhinstall_community_view;
}

/**
 * Access callback for mhinstall_community CRUD operations.
 */
function mhinstall_community_access($op, $mhinstall_community = NULL, $account = NULL) {
  if (($op == 'view' && user_access('view mhinstall_community', $account)) || user_access('administer mhinstall_community', $account)) {
    return TRUE;
  }
  else if (user_access('administer mhinstall_community', $account)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_permission().
 */
function mhinstall_community_permission() {
  return array(
    'view mhinstall_community' => array(
      'title' => t('View MH Install Community Entities'),      
    ),
    'administer mhinstall_community' => array(
      'title' => t('Administer MH Install Community Entities'),
    ),
  );
}
/**
 * Custom entity class for the mhinstall_community type.
 * The class being overriden is located in:
 * sites/all/modules/contrib/entity/includes/entity.inc
 */
class MHInstallCommunityEntity extends Entity {
  /**
   * Override this in order to implement a custom default URI.
   */
  protected function defaultUri() {
    return array('path' => 'mhinstall_community/' . $this->identifier());
  }
}

/**
 * Our custom controller for the mhinstall_community type.
 *
 * We're choosing to extend the controller provided by the entity module for
 * full CRUD support for item.
 *
 * The EntityAPIController is found in
 * sites/all/modules/contrib/entity/includes/entity.controller.inc
 */
class MHInstallCommunityEntityController extends EntityAPIController {
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $build = parent::buildContent($entity, $view_mode, $langcode, $content);
    // Build page here using render arrays.
    $build['id'] = array(
      '#type' => 'markup',
      '#markup' => 'The id of this entity is ' . $entity->id . '<br>',
    );
    $build['label'] = array(
      '#type' => 'markup',
      '#markup' => 'The label of this entity is ' . $entity->label . '<br>',
    );
    $build['created'] = array(
      '#type' => 'markup',
      '#markup' => 'This entity was created on ' . date('m-d-Y', $entity->created) . '<br>',
    );
    $build['updated'] = array(
      '#type' => 'markup',
      '#markup' => 'This entity was last updated on ' . date('m-d-Y', $entity->updated) . '<br>',
    );
    
    if ($view_mode == 'custom_view1') {
      $build['custom_view1'] = array(
        '#type' => 'markup',
        '#markup' => 'This is Custom View 1',
      );
    }
    
    return $build;
  }
  
  /**
   * Override save method.
   *
   * Populate created and updated dates automatically.
   */
  public function save($entity, DatabaseTransaction $transaction = NULL) {
    if (isset($entity->is_new)) {
      $entity->created = REQUEST_TIME;
    }
    
    $entity->updated = REQUEST_TIME;
    
    return parent::save($entity, $transaction);
  }
}

/**
 * Our custom controller for the admin ui.
 *
 * The EntityDefaultUIController can be found in
 * sites/all/modules/contrib/entity/includes/entity.ui.inc
 */
class MHInstallCommunityEntityUIController extends EntityDefaultUIController {
 /**
   * Generates the table headers for the overview table.
   */
  protected function overviewTableHeaders($conditions, $rows, $additional_header = array()) {
    $header = $additional_header;
    array_unshift($header, t('MH Install Community'));
    if (!empty($this->entityInfo['exportable'])) {
      $header[] = t('Status');
    }
    // Add operations with the right colspan.
    $header[] = array('data' => t('Operations'), 'colspan' => $this->operationCount());
    return $header;
  }

}

