<?php
/**
 * @file
 * Provides a custom entity type name 'mhinstall_customer'.
 */

/**
 * Implements hook_entity_info().
 */
function mhinstall_customer_entity_info() {
  $info = array();
  // The custom MHInstallCustomer entity is defined here.
  // See http://drupal.org/node/1026420 and http://drupal.org/node/878804
  // for more documentation.
  $info['mhinstall_customer'] = array(
    // Human readable label
    'label' => t('Customer'),
    'description' => t('Use this data type to store information about customers'),
    // Table for storing entity data, defined in hook_schema().
    'base table' => 'mhinstall_customer',
    // This helps Entity API know how to query the custom table.
    'entity keys' => array(
      'id' => 'id',
      'label' => 'label',
    ),
    // A simple wrapper around the uri method in the controller class.
    'uri callback' => 'entity_class_uri',
    // Default class is 'Entity',
    'entity class' => 'MHInstallCustomerEntity',
    // Default class is 'EntityAPIController',
    'controller class' => 'MHInstallCustomerEntityController',
    // The information below is used to extend the EntityDefaultUIController.
    'admin ui' => array(
      'path' => 'admin/mh-install/data-types/mhinstall_customer',
      'controller class' => 'MHInstallCustomerEntityUIController',
      'menu wildcard' => '%mhinstall_customer',
      'file' => 'mhinstall_customer.admin.inc',
    ),
    'module' => 'mhinstall_customer',
    // This controls who can access entity CRUD.
    'access callback' => 'mhinstall_customer_access',
    'fieldable' => TRUE,
    'bundles' => array(
      'mhinstall_customer' => array(
        'label' => t('Customer'),
        'admin' => array(
          'path' => 'admin/mh-install/data-types/mhinstall_customer',
          'access arguments' => array('administer mhinstall_customer'),
        ),
      ),
    ),
    'views controller class' => 'EntityDefaultViewsController',
    'view modes' => array(
      'custom_view1' => array(
        'label' => t('Custom View 1'),
        'custom settings' => FALSE,
      ),      
    ),
  );
  return $info;
}

/**
 * Implements hook_entity_property_info().
 */
function mhinstall_customer_entity_property_info() {
  $info = array();
  $properties = &$info['mhinstall_customer']['properties'];
  $properties['id'] = array(
    'label' => t('EID'),
    'description' => t('The unique, numeric, internal ID of the mhinstall_customer entity.'),
    'type' => 'integer',
    'schema field' => 'id',
  );
  $properties['label'] = array(
    'label' => t('mhinstall_customer entity ID'),
    'description' => t('The unique human readable ID of the mhinstall_customer entity.'),
    'type' => 'text',
    'schema field' => 'label',
  );
  $properties['created'] = array(
    'label' => t('Created date'),
    'description' => t('The date the mhinstall_customer entity was created.'),
    'type' => 'date',
    'schema field' => 'created',
  );
  $properties['updated'] = array(
    'label' => t('Updated date'),
    'description' => t('The date the mhinstall_customer entity was last updated.'),
    'type' => 'date',
    'schema field' => 'updated',
  );
  return $info;
}

/**
 * Implements hook_menu().
 */
function mhinstall_customer_menu() {
  $items = array();
  $items['mhinstall_customer/%mhinstall_customer'] = array(
    'title' => 'MH Install Customer entity',
    'page callback' => 'mhinstall_customer_view_entity',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Menu autoloader for /mhinstall_customer/%mhinstall_customer.
 */
function mhinstall_customer_load($id) {
  $mhinstall_customer = entity_load('mhinstall_customer', array($id));
  return array_pop($mhinstall_customer);
}

/**
 * Callback for /mhinstall_customer/ID page.
 *
 * A place to render a complete video entity.
 */
function mhinstall_customer_view_entity($mhinstall_customer) {
  // Use any of the view modes defined in hook_entity_info().
  $viewmode = 'full'; 
  drupal_set_title($mhinstall_customer->label);
  $mhinstall_customer_view = entity_view('mhinstall_customer', array($mhinstall_customer->id => $mhinstall_customer), $viewmode);
  dsm($mhinstall_customer, 'The results from entity_load()');
  dsm($mhinstall_customer_view, 'The results from entity_view()');
  return $mhinstall_customer_view;
}

/**
 * Access callback for mhinstall_customer CRUD operations.
 */
function mhinstall_customer_access($op, $mhinstall_customer = NULL, $account = NULL) {
  if (($op == 'view' && user_access('view mhinstall_customer', $account)) || user_access('administer mhinstall_customer', $account)) {
    return TRUE;
  }
  else if (user_access('administer mhinstall_customer', $account)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_permission().
 */
function mhinstall_customer_permission() {
  return array(
    'view mhinstall_customer' => array(
      'title' => t('View MH Install Customer Entities'),      
    ),
    'administer mhinstall_customer' => array(
      'title' => t('Administer MH Install Customer Entities'),
    ),
  );
}
/**
 * Custom entity class for the MHInstallCustomer type.
 * The class being overriden is located in:
 * sites/all/modules/contrib/entity/includes/entity.inc
 */
class MHInstallCustomerEntity extends Entity {
  /**
   * Override this in order to implement a custom default URI.
   */
  protected function defaultUri() {
    return array('path' => 'mhinstall_customer/' . $this->identifier());
  }
}

/**
 * Our custom controller for the MHInstallCustomer type.
 *
 * We're choosing to extend the controller provided by the entity module for
 * full CRUD support for item.
 *
 * The EntityAPIController is found in
 * sites/all/modules/contrib/entity/includes/entity.controller.inc
 */
class MHInstallCustomerEntityController extends EntityAPIController {
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $build = parent::buildContent($entity, $view_mode, $langcode, $content);
    // Build page here using render arrays.
    $build['id'] = array(
      '#type' => 'markup',
      '#markup' => 'The id of this entity is ' . $entity->id . '<br>',
    );
    $build['label'] = array(
      '#type' => 'markup',
      '#markup' => 'The label of this entity is ' . $entity->label . '<br>',
    );
    $build['created'] = array(
      '#type' => 'markup',
      '#markup' => 'This entity was created on ' . date('m-d-Y', $entity->created) . '<br>',
    );
    $build['updated'] = array(
      '#type' => 'markup',
      '#markup' => 'This entity was last updated on ' . date('m-d-Y', $entity->updated) . '<br>',
    );
    
    if ($view_mode == 'custom_view1') {
      $build['custom_view1'] = array(
        '#type' => 'markup',
        '#markup' => 'This is Custom View 1',
      );
    }
    
    return $build;
  }
  
  /**
   * Override save method.
   *
   * Populate created and updated dates automatically.
   */
  public function save($entity, DatabaseTransaction $transaction = NULL) {
    if (isset($entity->is_new)) {
      $entity->created = REQUEST_TIME;
    }
    
    $entity->updated = REQUEST_TIME;
    
    return parent::save($entity, $transaction);
  }
}

/**
 * Our custom controller for the admin ui.
 *
 * The EntityDefaultUIController can be found in
 * sites/all/modules/contrib/entity/includes/entity.ui.inc
 */
class MHInstallCustomerEntityUIController extends EntityDefaultUIController {
 /**
   * Generates the table headers for the overview table.
   */
  protected function overviewTableHeaders($conditions, $rows, $additional_header = array()) {
    $header = $additional_header;
    array_unshift($header, t('MHInstallCustomer'));
    if (!empty($this->entityInfo['exportable'])) {
      $header[] = t('Status');
    }
    // Add operations with the right colspan.
    $header[] = array('data' => t('Operations'), 'colspan' => $this->operationCount());
    return $header;
  }

}

